baseURL = 'http://localhost:1313'
languageCode = 'ko-KR'
title = 'Obsidian Vault'
# theme = "hextra"

# 빌드 시 무시할 파일 및 디렉토리 설정
ignoreFiles = [
  'content/02.inbox/Notion/',
  'content/05.clipping/*',
  'content/07.Daliy Note/',
  'content/89.Obsidian/',
  'content/index.html'
]

[taxonomies]
  tags = "tags"
  categorys = "categories"
  series = "series"

# canonifyURLs = true
# 로그에서 'goldmark 원시 HTML(raw HTML) 경고'를 무시합니다.
# ignoreLogs = ['content/05.clipping/*']

# 마크업(Markup) 설정
[markup]
  # Goldmark 마크다운 렌더러 설정
  [markup.goldmark]
    # 렌더러(renderer) 관련 옵션
    [markup.goldmark.renderer]
      # 콘텐츠 내 원시 HTML 태그를 허용하여 렌더링합니다.
      unsafe = true
  