# baseURL = 'https://shinnyeonki.github.io/obsidian_repo'
# baseURL = 'http://shinnk.iptime.org/memo'
# baseURL = 'http://memo.shinnk.kro.kr/'
baseURL = 'http://localhost:1313'


languageCode = 'ko-KR'
title = 'Obsidian Vault'
# theme = "hextra"
hasCJKLanguage = true

# 빌드 시 무시할 파일 및 디렉토리 설정
ignoreFiles = [
  'content/02.inbox/Notion/',
  'content/05.clipping/',
  'content/07.Daliy Note/',
  'content/89.Obsidian/',
  'content/index.html'
]

[taxonomies]
  tags = "tags"
  categorys = "categories"
  series = "series"

# canonifyURLs = true
# 로그에서 'goldmark 원시 HTML(raw HTML) 경고'를 무시합니다.
# ignoreLogs = ['content/05.clipping/*']

[params]
  copyright = "© 2024 Shinnk. All rights reserved."
  description = "obsidian 으로 편집하고 hugo 로 빌드하는 개인 블로그 및 노트 저장소입니다. 폴더별, tag별, 시리즈별 등 다양한 분류 체계를 지원합니다."

# 마크업(Markup) 설정
[markup]
  # Goldmark 마크다운 렌더러 설정
  [markup.goldmark]
    # 렌더러(renderer) 관련 옵션
    [markup.goldmark.renderer]
      # 콘텐츠 내 원시 HTML 태그를 허용하여 렌더링합니다.
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false
# # 1. 새로운 미디어 타입 정의
# [mediaTypes]
#   [mediaTypes."text/markdown"]
#     suffixes = ["md"]

# # 2. 새로운 출력 형식 정의
# [outputFormats]
#   [outputFormats.rawmd] # "rawmd"는 원하는 이름으로 지정 가능
#     mediaType = "text/markdown"
#     baseName = "index"      # 출력 파일명을 index.md로 설정
#     isPlainText = true      # Hugo의 템플릿 엔진을 거치지 않음
#     path = "raw"            # /public/raw/ 디렉토리에 결과물을 저장

# [outputs]
#   page = ["HTML", "rawmd"] # 모든 일반 페이지에 HTML과 rawmd 출력을 모두 생성
#   home = ["HTML", "RSS"] # 홈페이지는 기존 설정 유지 (필요시 "rawmd" 추가)

# [permalinks]
#   # 'page' 종류의 콘텐츠가 'rawmd' 형식으로 출력될 때의 URL 규칙
#   # "/:slug"는 "/무제-1" 과 같은 경로를 생성하고, Hugo는 여기에 확장자(.md)를 붙여줍니다.
#   page.rawmd = "/:slug"
